package apperror

// LATER: This file will be auto-generated by our dictionary tool.

// ErrorCode is the general system-level error category.
type ErrorCode string

const (
	CodeNotFound         ErrorCode = "NOT_FOUND"
	CodeConflict         ErrorCode = "CONFLICT"
	CodeValidationFailed ErrorCode = "VALIDATION_FAILED"
	CodeForbidden        ErrorCode = "FORBIDDEN"
	CodeUnauthorized     ErrorCode = "UNAUTHORIZED"
	CodeInternalError    ErrorCode = "INTERNAL_SERVER_ERROR"
	CodeBadRequest       ErrorCode = "BAD_REQUEST"
)

// BusinessCode is the specific, fine-grained business reason.
type BusinessCode string

const (
	// Generic business codes
	BusinessCodeGeneral BusinessCode = "GENERAL"

	// User-specific business codes
	BusinessCodeUserNotFound     BusinessCode = "USER_NOT_FOUND"
	BusinessCodeEmailExists      BusinessCode = "EMAIL_ALREADY_EXISTS"
	BusinessCodeUsernameExists   BusinessCode = "USERNAME_ALREADY_EXISTS"
	BusinessCodeInvalidEmail     BusinessCode = "INVALID_EMAIL"
	BusinessCodeInvalidUsername  BusinessCode = "INVALID_USERNAME"
	BusinessCodeAccountSuspended BusinessCode = "ACCOUNT_SUSPENDED"
	BusinessCodeSupabaseIDExists BusinessCode = "SUPABASE_ID_ALREADY_EXISTS"

	// Role-specific business codes
	BusinessCodeRoleNotFound         BusinessCode = "ROLE_NOT_FOUND"
	BusinessCodeRoleNameExists       BusinessCode = "ROLE_NAME_ALREADY_EXISTS"
	BusinessCodeRoleAlreadyAssigned  BusinessCode = "ROLE_ALREADY_ASSIGNED"
	BusinessCodeRoleNotAssigned      BusinessCode = "ROLE_NOT_ASSIGNED"
	BusinessCodeCannotUpdateSystem   BusinessCode = "CANNOT_UPDATE_SYSTEM_ROLE"
	BusinessCodeCannotDeleteSystem   BusinessCode = "CANNOT_DELETE_SYSTEM_ROLE"
	BusinessCodeTemplateCannotAssign BusinessCode = "TEMPLATE_ROLE_CANNOT_ASSIGN"

	// Permission-specific business codes
	BusinessCodePermissionNotFound BusinessCode = "PERMISSION_NOT_FOUND"
	BusinessCodeInvalidPermission  BusinessCode = "INVALID_PERMISSION"
	BusinessCodePermissionDenied   BusinessCode = "PERMISSION_DENIED"

	// Validation-specific business codes
	BusinessCodeMissingRequiredField BusinessCode = "MISSING_REQUIRED_FIELD"
	BusinessCodeInvalidFormat        BusinessCode = "INVALID_FORMAT"
	BusinessCodeValueTooLong         BusinessCode = "VALUE_TOO_LONG"
	BusinessCodeValueTooShort        BusinessCode = "VALUE_TOO_SHORT"

	// Post-specific business codes
	BusinessCodePostNotFound            BusinessCode = "POST_NOT_FOUND"
	BusinessCodeSlugAlreadyExists       BusinessCode = "SLUG_ALREADY_EXISTS"
	BusinessCodeInvalidStatusTransition BusinessCode = "INVALID_STATUS_TRANSITION"
	BusinessCodeCannotAddToTheme        BusinessCode = "CANNOT_ADD_TO_THEME"

	// Theme-specific business codes
	BusinessCodeThemeNotFound      BusinessCode = "THEME_NOT_FOUND"
	BusinessCodeThemeNameExists    BusinessCode = "THEME_NAME_ALREADY_EXISTS"
	BusinessCodePostAlreadyInTheme BusinessCode = "POST_ALREADY_IN_THEME"
	BusinessCodePostNotInTheme     BusinessCode = "POST_NOT_IN_THEME"
)
