name: Backend CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    name: CI Pipeline
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      
      - name: Install just
        uses: extractions/setup-just@v2
      
      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/go/bin
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      
      - name: Install development tools
        run: just install-tools
      
      - name: Download dependencies and tidy
        run: just tidy
      
      - name: Generate code
        run: just generate
      
      - name: Check formatting
        run: |
          cd backend
          if [ -n "$(gofumpt -l -d .)" ]; then
            echo "Code is not formatted. Please run 'just fmt'"
            gofumpt -l -d .
            exit 1
          fi
      
      - name: Run go vet
        run: |
          cd backend
          go vet ./...
      
      - name: Run tests
        run: just test
      
      - name: Run linter
        run: just lint
      
      - name: Run vulnerability check
        run: |
          cd backend
          govulncheck ./...
      
      - name: Build verification
        run: just build